### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by maxnov1** [ChinaYi/Hard-Frame-Detection-and-Online-Mapping-for-Surgical-Phase-Recognition#2]
Hello! I have a problem.

Traceback (most recent call last):
  File "main.py", line 135, in <module>
    feature, res = resnet50(imgs.view(-1, c, h, w))
  File "C:\ProgramData\Anaconda3\natasha\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Natalia\Downloads\miccai19-master\OHFM\model.py", line 34, in forward
    feature = self.features(x).view(-1, 2048)
  File "C:\ProgramData\Anaconda3\natasha\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\natasha\lib\site-packages\torch\nn\modules\container.py", line 100, in forward
    input = module(input)
  File "C:\ProgramData\Anaconda3\natasha\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\natasha\lib\site-packages\torch\nn\modules\pooling.py", line 554, in forward
    self.padding, self.ceil_mode, self.count_include_pad, self.divisor_override)
  File "C:\ProgramData\Anaconda3\natasha\lib\site-packages\torch\nn\modules\module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'AvgPool2d' object has no attribute 'divisor_override'

How can I fix it? Thank you!

**Comment by maxnov1** [comment]
I have latest versions of Pytorch and Torchvision.

**Comment by ChinaYi** [comment]
Hi, maybe you can use Pytorch==0.4.

**Comment by maxnov1** [comment]
If i try to use 0.4.0 ver. i get this problem. Maybe, i need to use specific version of torchvision?

(C:\ProgramData\Anaconda3\natasha) C:\Users\Natalia\Downloads\miccai19-master\OHFM>python main.py --dataset=cholec80-workflow-5 --savepath=test_result
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from dataset import *
  File "C:\Users\Natalia\Downloads\miccai19-master\OHFM\dataset.py", line 4, in <module>
    import utils
  File "C:\Users\Natalia\Downloads\miccai19-master\OHFM\utils.py", line 4, in <module>
    from torchvision.transforms import *
  File "C:\ProgramData\Anaconda3\natasha\lib\site-packages\torchvision\__init__.py", line 3, in <module>
    from torchvision import models
  File "C:\ProgramData\Anaconda3\natasha\lib\site-packages\torchvision\models\__init__.py", line 5, in <module>
    from .inception import *
  File "C:\ProgramData\Anaconda3\natasha\lib\site-packages\torchvision\models\inception.py", line 8, in <module>
    from torch.jit.annotations import Optional
ModuleNotFoundError: No module named 'torch.jit.annotations'

**Comment by ChinaYi** [comment]
torchvision==0.2.0


------------------ Original ------------------

**Comment by maxnov1** [comment]
I have a few more questions. 

What machine learning methods were used to train the system?

Is training provided by tracking medical instruments or anatomical structures?  Is any model used to improve classification results?

thank you in advance.
